### ISSUE TITLE
keycloak_realm_user_profile: should support 'unmanagedAttributePolicy'

### ISSUE THREAD

**Issue by scottescue** [keycloak/terraform-provider-keycloak#946]
The `unmanagedAttributePolicy` attribute has been added to the [User Profile Config definition](https://www.keycloak.org/docs-api/24.0.2/rest-api/index.html#UPConfig) as of Keycloak version 24. This is exposed in the Admin UI as the _Unmanaged Attributes_ realm setting.

Allowed values are:
- _omitted_ - Disabled
- `ENABLED` - Enabled
- `ADMIN_VIEW` - Only administrators can view
- `ADMIN_EDIT` - Only administrators can write

The provider should allow this new attribute to be set in the `keycloak_realm_user_profile` resource.

**Comment by ericwalterb** [comment]
This is something we also hope gets added.  Since upgrading to Keycloak 24, we have to manually enable Unmanaged Attributes. However, every time we run the terraform plan, it gets set back to null.

**Comment by bradhead** [comment]
@ericwalterb  Were you able to apply the keycloak_realm_user_profile resource at all? I get a failure that username can't be removed.. I am not trying to remove it.. seems the state thinks it is creating the profile for the first time and it does not support import.  Did you sort out how to set unmanaged attributes?

**Comment by soulchild** [comment]
@ericwalterb Interesting! We have the option manually set to "Only administrators can write" and a Terraform run does not seem to touch/change the option. Are you sure you're seeing changes to the option after applying the Terraform plan? I'm really worried that this gets reset without us noticing which would cause a lot of headaches for us.

**Comment by grolingm-VU** [comment]
We also had to manually enable the option. First, we left the option to the default value. We have a number of users that we import through this provider and stored a number of custom user attributes (now called _unmanaged user attributes_) on these users. Having the default keycloak completely ignores these user attributes and doesn't even store them. 

Currently, we have to enable this option manually after each installation of the keycloak. This is very tideous work as we switch between both instances of the cluster after each deployment and those instances are set-up from scratch. I really appreaciate the option to have managed and unmanaged user attributes as it would give us a better handling of user attributes in general. However, having neither the possibility to enable the option nor the possibility to really define all managed attributes via _keycloak_realm_user_profile_ is a challenging problem. 

There are two discussions open targeting the problem on a broader level:
https://github.com/mrparkers/terraform-provider-keycloak/issues/944
and 
https://github.com/mrparkers/terraform-provider-keycloak/issues/964

**Comment by CMithilReddy** [comment]
Hi, is it possible to add unmanagedAttributePolicy as a custom attribute to Keycloak_realm resource ?? I followed this documentation https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/realm#attributes and did something like:

```
resource "keycloak_realm" "realm" {
   realm                          = var.realm_name
   enabled                        = var.realm_enabled
   display_name                   = var.display_name
   attributes  = {
    unmanagedAttributePolicy    = "ENABLED"
     }
  }
``` 
On applying the terraform state changes to our dev instance, the changes were not applied to the realm. Could some one help me on this issue. Thank you !!

**Comment by onlyTars** [comment]
Is there anything new on this subject? We encounter the same problem

**Comment by jpetre0** [comment]
Any update on this please? We are also encountering the same issue

**Comment by MartinNowak** [comment]
> Hi, is it possible to add unmanagedAttributePolicy as a custom attribute to Keycloak_realm resource ?? I followed this documentation https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs/resources/realm#attributes and did something like:

No, it's part of the user profile configuration.

**Comment by sschu** [comment]
Implemented by https://github.com/keycloak/terraform-provider-keycloak/pull/1042

**Comment by soulchild** [comment]
@sschu Setting the `unmanaged_attribute_policy` with the new `v5.0.0` of the provider like so:

```
resource "keycloak_realm_user_profile" "my_userprofile" {
  realm_id                   = keycloak_realm.my_realm.id
  unmanaged_attribute_policy = "ADMIN_EDIT"
}
```

gives me the following error:

```
error sending PUT request to /admin/realms/my_realm/users/profile: 400 Bad Request. Response body: {"errorMessage":"[The attribute 'username' can not be removed, The attribute 'email' can not be removed]"}
```

This is a legacy installation which doesn't (yet) define dedicated user profile attributes, so I was hoping I could just set the GUI setting "Unmanaged attributes" to "Only administrators can write" with the above configuration. Am I holding it wrong or is this a bug?

**Comment by sschu** [comment]
@soulchild The user profile is always enabled so you always have to define a valid user profile containing at least username as required attribute and email.
